## Where the samples will be written
save_data: selkup/run/example
## Where the vocab(s) will be written
src_vocab: selkup/run/selkup.vocab.src
tgt_vocab: selkup/run/selkup.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: True



#both_embeddings: vectors.txt
src_embeddings: selkup_embs.txt
tgt_embeddings: selkup_rusembs.txt
embeddings_type: "word2vec"
src_word_vec_size: 5573
tgt_word_vec_size: 3559



# Corpus opts:
data:
    corpus_1:
        path_src: low_resource_mt/datasets/selkup/src-train.txt
        path_tgt: low_resource_mt/datasets/selkup/tgt-train.txt
    valid:
        path_src: low_resource_mt/datasets/selkup/src-val.txt
        path_tgt: low_resource_mt/datasets/selkup/tgt-val.txt

# Vocabulary files that were just created
src_vocab: selkup/run/selkup.vocab.src
tgt_vocab: selkup/run/selkup.vocab.tgt

#train_from: selkup/run/model_step_77000.pt

# Train on a single GPU
world_size: 2
gpu_ranks: [0,1]

# Where to save the checkpoints
save_model: selkup/run/model
save_checkpoint_steps: 1000
train_steps: 80000
valid_steps: 1000

optim: adam
learning_rate: 0.00001