
## Where the samples will be written
save_data: karelian/run/example
## Where the vocab(s) will be written
src_vocab: karelian/run/karelian.vocab.src
tgt_vocab: karelian/run/karelian.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: True

src_embeddings: glove_vepkar_vectors.txt
tgt_embeddings: glove_rus_vectors.txt
#tgt_embeddings: glove/vectors.txt
embeddings_type: "GloVe"
src_word_vec_size: 50
tgt_word_vec_size: 100


# Corpus opts:
data:
    corpus_1:
        path_src: low_resource_mt/datasets/karelian/src-train.txt
        path_tgt: low_resource_mt/karelian/tgt-train.txt
        #transforms: [onmt_tokenize]
    valid:
        path_src: low_resource_mt/datasets/karelian/src-val.txt
        path_tgt: low_resource_mt/datasets/karelian/tgt-val.txt
        #transforms: [onmt_tokenize]

# Vocabulary files that were just created
src_vocab: karelian/run/karelian.vocab.src
tgt_vocab: karelian/run/karelian.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

#batch_size: 1
#valid_batch_size: 1

# Where to save the checkpoints
save_model: karelian/run/model
save_checkpoint_steps: 1000
train_steps: 80000
valid_steps: 1000

optim: adam
learning_rate: 0.00001